print('                                                             March 17 2023')
print('Today i am feeling pretty stressed but, using Codedex to re-teach myself')
print('python is helping me relax a bit more.')
print('In one month from now, I want to complete the python series on Codedex and')
print('move on to the HTML series.')
print('A message to my future programmer self is to focus on yourself and your own')
print('personal learning journey. Do not compare yourself to others around you.')
print('Progress is not linear, take things one day at a time.')
print(':)')